version: '3.7'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
        environment: 
      - SECRET_KEY==1^bv_am36())e&7r+t43%g+cj-^^uom8f+m%kg@a(np4x^_*m
      - DEBUG=1
      - STRIPE_TEST_PUBLISHABLE_KEY=<pk_test_51Jc3EaBvEyqc6wMG3o9sufOgXwquIW4bJMS7S2o8IM9ImW5mnKRX29DiFuWlTnjp3m1lQYx1RJDTQIEm2r5yvKPN00XjlcdyiE>
      - STRIPE_TEST_SECRET_KEY=<sk_test_51Jc3EaBvEyqc6wMGma0QqLAcz9FPvTpiM47Q7m734YqrNOwhZJZex9L8vJsdbgPRa24wytb8wAxiBb8bJt66ygEM00u5CU5JFw>
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on: 
      - db
  db:
    image: postgres:11
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

volumes: 
  postgres_data: